from datetime import datetime, timezone
from pathlib import Path
from typing import Dict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

_REPORT_DIR = Path("data/reports")

_FONT_FAMILY = [
    "DejaVu Sans",
    "Noto Sans Arabic",
    "Arial Unicode MS",
    "sans-serif",
]


def build_pdf_report(result: Dict) -> Path:
    _REPORT_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    out = _REPORT_DIR / f"urdustack_report_{ts}.pdf"

    orig_font = matplotlib.rcParams.get("font.sans-serif", [])
    matplotlib.rcParams["font.sans-serif"] = _FONT_FAMILY

    try:
        with PdfPages(str(out)) as pdf:
            _page_summary(pdf, result)
            _page_detail(pdf, result)
    finally:
        matplotlib.rcParams["font.sans-serif"] = orig_font

    return out


def _header(fig, title):
    fig.text(
        0.5, 0.96, title, ha="center", va="top",
        fontsize=18, fontweight="bold", color="#2c3e50",
    )
    fig.text(
        0.5, 0.925, "UrduStack \u2014 Unified Urdu NLP Analysis",
        ha="center", va="top", fontsize=10, color="#7f8c8d",
    )
    fig.plot([0.08, 0.92], [0.915, 0.915], color="#bdc3c7", lw=0.8)


def _footer(fig):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    fig.text(
        0.5, 0.015,
        f"Generated by UrduStack | {ts}",
        ha="center", va="bottom", fontsize=7, color="#bdc3c7",
    )


def _section(fig, y, label):
    fig.text(0.08, y, label, ha="left", va="top",
             fontsize=12, fontweight="bold", color="#34495e")
    return y - 0.035


def _body(fig, y, text, size=9, color="#2c3e50"):
    import textwrap
    lines = textwrap.wrap(str(text), width=95)
    for ln in lines:
        if y < 0.06:
            break
        fig.text(0.08, y, ln, ha="left", va="top", fontsize=size, color=color)
        y -= 0.023
    return y


def _page_summary(pdf, r):
    fig = plt.figure(figsize=(8.5, 11))
    _header(fig, "Analysis Report")
    y = 0.89

    score = r.get("risk_score", 0.0)
    conf = r.get("risk_confidence", 0.0)
    level = r.get("risk_level", "unknown").upper()
    cmap = {"HIGH": "#e74c3c", "MEDIUM": "#f39c12", "LOW": "#27ae60"}
    col = cmap.get(level, "#95a5a6")

    ax = fig.add_axes([0.08, 0.73, 0.84, 0.14])
    ax.set_xlim(0, 3)
    ax.set_ylim(0, 1)
    ax.axis("off")

    for i, (val, lbl, c) in enumerate([
        (f"{score:.2f}", "Risk Score", col),
        (f"{conf:.2f}", "Confidence", "#3498db"),
        (level, "Risk Level", col),
    ]):
        x = 0.5 + i
        ax.add_patch(plt.Rectangle((x - 0.38, 0.05), 0.76, 0.9,
                                   facecolor=c, alpha=0.08,
                                   edgecolor=c, lw=1.5, zorder=1))
        ax.text(x, 0.62, val, ha="center", va="center",
                fontsize=22, fontweight="bold", color=c, zorder=2)
        ax.text(x, 0.2, lbl, ha="center", va="center",
                fontsize=9, color="#7f8c8d", zorder=2)

    y = 0.70
    y = _section(fig, y, "Input Text")
    y = _body(fig, y, r.get("original_text", ""))

    y -= 0.015
    y = _section(fig, y, "Normalized Text")
    nc = r.get("norm_confidence", 0.0)
    y = _body(fig, y, f"(confidence {nc:.2f}) {r.get('normalized', '')}", size=8)

    y -= 0.015
    y = _section(fig, y, "Explanation")
    y = _body(fig, y, r.get("explanation", ""))

    flagged = r.get("flagged_phrases", [])
    if flagged:
        y -= 0.015
        phrases = [p["phrase"] for p in flagged[:6]]
        contribs = [p["contribution"] for p in flagged[:6]]
        bottom = max(y - 0.14, 0.06)
        h = y - bottom
        ax2 = fig.add_axes([0.08, bottom, 0.84, h])
        colors = [
            "#e74c3c" if c >= 0.3 else "#f39c12" if c >= 0.15 else "#27ae60"
            for c in contribs
        ]
        ypos = range(len(phrases))
        ax2.barh(ypos, contribs, color=colors, height=0.6)
        ax2.set_yticks(ypos)
        ax2.set_yticklabels(phrases, fontsize=8)
        ax2.set_xlabel("Risk Contribution", fontsize=8)
        ax2.set_title("Phrase Contributions", fontsize=10, fontweight="bold")
        ax2.invert_yaxis()
        if contribs:
            ax2.set_xlim(0, max(contribs) * 1.15)
        ax2.tick_params(axis="x", labelsize=7)
        for i, (c, p) in enumerate(zip(contribs, phrases)):
            ax2.text(c + 0.003, i, f"{c:.3f}", va="center", fontsize=7)
        y = bottom - 0.01

    _footer(fig)
    pdf.savefig(fig)
    plt.close(fig)


def _page_detail(pdf, r):
    fig = plt.figure(figsize=(8.5, 11))
    _header(fig, "Detailed Analysis")
    y = 0.89

    entities = r.get("entities", [])
    if entities:
        y = _section(fig, y, "Entities Detected")
        for e in entities[:8]:
            if y < 0.06:
                break
            fig.text(
                0.1, y,
                f"\u2022  {e['word']}  \u2014  {e['entity_group']}  "
                f"(confidence {e['score']:.2f})",
                ha="left", va="top", fontsize=9, color="#2c3e50",
            )
            y -= 0.023
        y -= 0.01

    ctx = r.get("entity_context", [])
    if ctx:
        y = _section(fig, y, "Entity Context")
        for c in ctx:
            if y < 0.06:
                break
            fig.text(0.1, y, f"\u2022  {c}", ha="left", va="top",
                     fontsize=9, color="#2c3e50")
            y -= 0.023
        y -= 0.01

    flagged = r.get("flagged_phrases", [])
    if flagged:
        y = _section(fig, y, "Flagged Phrases (Detail)")
        for p in flagged[:10]:
            if y < 0.06:
                break
            fig.text(
                0.1, y,
                f"\u2022  \"{p['phrase']}\"  \u2014  "
                f"contribution: {p['contribution']:.3f}",
                ha="left", va="top", fontsize=9, color="#2c3e50",
            )
            y -= 0.023
        y -= 0.01

    simplified = r.get("simplified_explanation", "")
    explanation = r.get("explanation", "")
    if simplified and simplified != explanation:
        y = _section(fig, y, "Plain Language Explanation")
        y = _body(fig, y, simplified)
        y -= 0.01

    y = _section(fig, y, "Recommendation")
    rec = r.get("recommendation", "No specific recommendation.")
    ax = fig.add_axes([0.06, max(y - 0.08, 0.05), 0.88, 0.08])
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    ax.add_patch(plt.Rectangle((0, 0), 1, 1,
                               facecolor="#3498db", alpha=0.08,
                               edgecolor="#3498db", lw=1))
    import textwrap
    rec_lines = textwrap.wrap(rec, width=85)
    for i, ln in enumerate(rec_lines[:4]):
        ax.text(0.03, 0.82 - i * 0.22, ln, ha="left", va="top",
                fontsize=9, color="#2c3e50")

    _footer(fig)
    pdf.savefig(fig)
    plt.close(fig)
